version: "3.8"

services:
  postgres:
    image: postgres:13
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=osmait
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app

  testdb:
    image: postgres:13
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
