import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../../styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import { cn } from "../../lib/utils";
import TeamSwitcher from "@/components/team-switcher";
import { MainNav } from "@/components/main-nav";

import { UserNav } from "@/components/user-nav";
import { Search } from "@/components/search";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ModeToggle /> */}
          <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow-md md:shadow-xl ">
            <div className=" md:flex md:h-16 items-center px-4">
              <TeamSwitcher />
              <MainNav className="mx-6 my-6 md:flex" />
              <div className=" ml-auto flex items-center space-x-4 mb-5 md:mb-0 justify-between ">
                <Search />
                <UserNav />
              </div>
            </div>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
