POST https://gestor-api.onrender.com/user
content-type: application/json

{
    "name":"Demo",
    "last_name":"Demo",
    "email":"demo@demo.com",
    "password":"12345678"
}

GET http://localhost:8080/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJab29YUTZpVlpnb1g3cE05SE9oMExZY2g1SiIsImV4cCI6MTcwNTQzMTk2Mn0.FQwynZSIGh-g0mGiRFh5cs2jAQEPAgv3FNBaIiVP51Q
