name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Change to Backend Directory
        run: cd BackEnd/
      - name: init mod
        run: go mod init "github.com/gestordegastos"
      - name: install dep
        run: go mod tidy
      - name: Test
        run: go test -v ./...
