name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Change to Backend Directory
        run: cd Backend/src

      - name: Test
        run: go test -v ./..
