name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: run docker for db test
        run: docker-compose up -d testdb
        working-directory: ./BackEnd

      - name: install dep
        run: go mod tidy
        working-directory: ./BackEnd
      - name: Test
        run: go test -v ./...
        working-directory: ./BackEnd
