name: Playwright Tests
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: run backend
        run: docker-compose up -d app postgres app-front
        working-directory: ./BackEnd

      - name: Install dependencies
        run: sudo npm ci
        working-directory: ./Frontend/gestor-presupuesto

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./Frontend/gestor-presupuesto

      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: ./Frontend/gestor-presupuesto
